import ApplyForm from "@/components/Apply/ApplyForm";
import HeroBanner from "@/components/Global/HeroBanner";
import GlobalNavbar from "@/components/Global/GlobalNavbar";
import AuthButton from "@/components/auth/AuthButton";
import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";

export default function index() {
  const { status } = useSession();
  return (
    <div>
      <Head>
        <title>Apply</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <GlobalNavbar />
      <HeroBanner title={"Apply Now"} />
      {status === "authenticated" ? (
        <ApplyForm />
      ) : (
        <div className="w-full mx-auto text-center py-8">
          <AuthButton />
        </div>
      )}
    </div>
  );
}
