export const data = [
  {
    state: "andaman&nicobar",
    priority1: "rowing",
    priority2: "athletics",
    priority3: "cycling",
  },
  {
    state: "andhrapradesh",
    priority1: "weightlifting",
    priority2: "archery",
    priority3: "athletics",
  },
  {
    state: "arunachalpradesh",
    priority1: "weightlifting",
    priority2: "archery",
    priority3: "judo",
  },
  {
    state: "assam",
    priority1: "boxing",
    priority2: "shooting",
    priority3: "weightlifting",
  },
  {
    state: "bihar",
    priority1: "athletics",
    priority2: "weightlifting",
    priority3: "wrestling",
  },
  {
    state: "chandigarh",
    priority1: "hockey",
    priority2: "boxing",
    priority3: "rowing",
  },
  {
    state: "chhattisgarh",
    priority1: "archery",
    priority2: "athletics",
    priority3: "hockey",
  },
  {
    state: "dadra&nagarhaveli",
    priority1: "table tennis",
    priority2: "archery",
    priority3: "athletics",
  },
  {
    state: "delhi",
    priority1: "wrestling",
    priority2: "athletics",
    priority3: "boxing",
  },
  {
    state: "goa",
    priority1: "swimming",
    priority2: "badminton",
    priority3: "table tennis",
  },
  {
    state: "gujarat",
    priority1: "athletics",
    priority2: "table tennis",
    priority3: "archery",
  },
  {
    state: "haryana",
    priority1: "boxing",
    priority2: "badminton",
    priority3: "athletics",
  },
  {
    state: "himachalpradesh",
    priority1: "boxing",
    priority2: "athletics",
    priority3: "judo",
  },
  {
    state: "jammu&kashmir",
    priority1: "fencing",
    priority2: "rowing",
    priority3: "judo",
  },
  {
    state: "jharkhand",
    priority1: "archery",
    priority2: "hockey",
    priority3: "athletics",
  },
  {
    state: "karnataka",
    priority1: "swimming",
    priority2: "athletics",
    priority3: "shooting",
  },
  {
    state: "kerala",
    priority1: "athletics",
    priority2: "judo",
    priority3: "boxing",
  },
  {
    state: "ladakh",
    priority1: "archery",
    priority2: "boxing",
    priority3: "athletics",
  },
  {
    state: "lakshadweep",
    priority1: "athletics",
    priority2: "badminton",
    priority3: "swimming",
  },
  {
    state: "madhyapradesh",
    priority1: "shooting",
    priority2: "hockey",
    priority3: "rowing",
  },
  {
    state: "maharashtra",
    priority1: "shooting",
    priority2: "athletics",
    priority3: "cycling",
  },
  {
    state: "manipur",
    priority1: "weightlifting",
    priority2: "archery",
    priority3: "hockey",
  },
  {
    state: "meghalaya",
    priority1: "boxing",
    priority2: "archery",
    priority3: "athletics",
  },
  {
    state: "mizoram",
    priority1: "boxing",
    priority2: "judo",
    priority3: "weightlifting",
  },
  {
    state: "nagaland",
    priority1: "wrestling",
    priority2: "archery",
    priority3: "boxing",
  },
  {
    state: "odisha",
    priority1: "hockey",
    priority2: "weightlifting",
    priority3: "athletics",
  },
  {
    state: "puducherry",
    priority1: "weightlifting",
    priority2: "badminton",
    priority3: "athletics",
  },
  {
    state: "punjab",
    priority1: "hockey",
    priority2: "shooting",
    priority3: "athletics",
  },
  {
    state: "rajasthan",
    priority1: "archery",
    priority2: "cycling",
    priority3: "shooting",
  },
  {
    state: "sikkim",
    priority1: "archery",
    priority2: "athletics",
    priority3: "boxing",
  },
  {
    state: "tamilnadu",
    priority1: "table tennis",
    priority2: "athletics",
    priority3: "fencing",
  },
  {
    state: "telangana",
    priority1: "rowing",
    priority2: "fencing",
    priority3: "weightlifting",
  },
  {
    state: "tripura",
    priority1: "judo",
    priority2: "swimming",
    priority3: "athletics",
  },
  {
    state: "uttarpradesh",
    priority1: "hockey",
    priority2: "athletics",
    priority3: "badminton",
  },
  {
    state: "uttarakhand",
    priority1: "athletics",
    priority2: "badminton",
    priority3: "boxing",
  },
];
