// import ApplyForm from "@/components/Apply/ApplyForm";
import ViewForm from "@/components/Form/ViewForm";
import GlobalNavbar from "@/components/Global/GlobalNavbar";
import HeroBanner from "@/components/Global/HeroBanner";
import AuthButton from "@/components/auth/AuthButton";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

export default function viewApplication() {
  const applicationId = useRouter().query.viewApplication;
  const { status } = useSession();

  return (
    <div>
      <Head>
        <title>Apply</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <GlobalNavbar />
      <HeroBanner title={`Application ID: ${applicationId}`} />
      {status === "authenticated" ? (
        <ViewForm applicationId={applicationId} />
      ) : (
        <div className="w-full mx-auto text-center py-8">
          <AuthButton />
        </div>
      )}
    </div>
  );
}
