import GlobalNavbar from "@/components/Global/GlobalNavbar";
import HeroBanner from "@/components/Global/HeroBanner";
import ApplicationCard from "@/components/User/ApplicationCard";
import { app, db } from "@/config/firebase";
import { doc, getDoc } from "firebase/firestore";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";

import { collection, query, where, getDocs } from "firebase/firestore";

export default function user() {
  const router = useRouter();
  const { data: session, status } = useSession();
  const [applications, setApplications] = React.useState([]);

  const user = router.query.user;

  async function getUserApplications(userId) {
    const tempArray = [];

    const q = query(
      collection(db, "applications"),
      where("applicant", "==", userId)
    );

    const querySnapshot = await getDocs(q);
    querySnapshot.forEach((doc) => {
      // doc.data() is never undefined for query doc snapshots
      console.log(doc.id, " => ", doc.data());

      tempArray.push({
        applicationID: doc.id,
        applicant: doc.data().applicant,
        status: doc.data().status,
      });
    });

    setApplications([...tempArray]);
  }

  React.useEffect(() => {
    if (status === "authenticated") {
      getUserApplications(session.user.email);
    }
  }, [status]);

  return (
    <>
      <Head>
        <title> {user} | Khelo India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <GlobalNavbar />
      <HeroBanner
        title={status === "authenticated" ? "Hello," + session.user.name : ""}
      />
      <div className="container mx-auto">
        <div className="container mx-auto flex flex-wrap title gap-4 py-4">
          {applications.map((application) => (
            <ApplicationCard
              applicationID={application.applicationID}
              key={application.applicationID}
              status={application.status}
            />
            //   console.log(application);
          ))}
          <div className="card w-96 bg-neutral text-neutral-content shadow-xl">
            <div className="card-body items-center text-center">
              <h2 className="card-title">No Applications?</h2>
              <div className="card-actions justify-end">
                <Link href={"/apply"} className="btn btn-primary">
                  Apply Now
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
